version: "3.8"

services:
  database:
    image: postgres
    container_name: dpspl-darp
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=reclusosdb
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
